// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://yjkirvfsljymprwldmzc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inlqa2lydmZzbGp5bXByd2xkbXpjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc4MzY1NTgsImV4cCI6MjA2MzQxMjU1OH0.h3BBI2tFF1etJnKOXcZGfe9fmBmv95nIK4i0dMu8kWE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);